### ISSUE TITLE
The token variable is specified more than once.

### ISSUE THREAD

**Issue by M-arcus** [shopware/shopware-cli-action#69]
```
/home/runner/work/_actions/shopware/shopware-cli-action/59ae24c10db19dc1a20836623b714d586dfdb9a8/dist/main/main.js:94382
    throw new Error(
    ^
Error: [@octokit/auth-action] The token variable is specified more than once. Use either `with.token`, `with.GITHUB_TOKEN`, or `env.GITHUB_TOKEN`. See https://github.com/octokit/auth-action.js#createactionauth
    at createActionAuth2 (/home/runner/work/_actions/shopware/shopware-cli-action/59ae24c10db19dc1a20836623b714d586dfdb9a8/dist/main/main.js:94382:11)
    at new Octokit (/home/runner/work/_actions/shopware/shopware-cli-action/59ae24c10db19dc1a20836623b714d586dfdb9a8/dist/main/main.js:94331:21)
    at new OctokitWithDefaults (/home/runner/work/_actions/shopware/shopware-cli-action/59ae24c10db19dc1a20836623b714d586dfdb9a8/dist/main/main.js:94250:11)
    at Object.<anonymous> (/home/runner/work/_actions/shopware/shopware-cli-action/59ae24c10db19dc1a20836623b714d586dfdb9a8/dist/main/main.js:96622:15)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1[28](https://github.com/bedarfde/bdrf-shop-v2/actions/runs/13036444435/job/36368204968#step:6:29)8:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49
Node.js v20.18.0
```

The code inside the GitHub Action Workflow file:
```yaml
      - name: Setup Shopware CLI
        uses: shopware/shopware-cli-action@59ae24c10db19dc1a20836623b714d586dfdb9a8 # v1.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
```
